model:
  # scale factor for normalising the openai clip (default value in SD)
  scale_factor: 0.6304
  # flow-matching model
  fm:
    target: scflow.cfm.FlowMatching
    params:
      sigma_min: 1e-8
      # config file for the UNet/UVit architecture
      net_cfg:
        target: scflow.models.kakaomodels.prior.PriorTransformer
        params:
          xf_width: 2048
          xf_layers: 12
          xf_heads: 32
          xf_final_ln: True
          clip_dim: 1536


data:
  target: scflow.dataloader.CustomDataModule
  params:
    train_npy: ./dataset/train.h5
    val_npy: ./dataset/test.h5
    num_workers: 4
    val_num_workers: 2
    train_group_size: 7000
    val_group_size: 3000
    batch_size: 384
    val_n_samples: 256
    val_batch_size: 4
    batches_per_epoch: 20000
    seed: 42


train:
  lr: 1e-5  #1e-5 match with bs 384
  weight_decay: 0.0
  lr_scheduler_patience: 20     # patience for LRPlateau scheduler on FID
  cal_metrics: True
  # exponential moving average
  ema_rate: 0.999
  ema_update_every: 1           # EMA update frequency
  ema_update_after_step: 1000   # warmup steps without EMA
  use_ema_for_sampling: True    # whether to use EMA model for sampling
  # checkpointing
  checkpoint_callback_params:    
    every_n_train_steps: 10000  # gradient update steps
    save_top_k: -1               # needs to be -1, otherwise it overwrites
    verbose: True
    save_last: False
    auto_insert_metric_name: False
  trainer_params:
    max_epochs: 16
    num_sanity_val_steps: 0
    accumulate_grad_batches: 1  
    log_every_n_steps: 50       # gradient update steps
    limit_val_batches: 64 #16        
    #check_val_every_n_epoch: 200     # steps, regardless of gradient accumulation
    val_check_interval: 10000
    precision: 16
  callbacks:
    - target: lightning.pytorch.callbacks.LearningRateMonitor
      params:
        logging_interval: 'step'
    - target: lightning.pytorch.callbacks.TQDMProgressBar
      params:
        refresh_rate: 2000
